### ISSUE TITLE
on the arcade i go invisble for some reason

### ISSUE THREAD

**Issue by the-good-1** [Celestial-Network/Issues#3]
Randomly during arcade I get invisibility

**Comment by IcedCode** [comment]
I have noticed this is mainly during Spleef and Skywars matches
Issue is unkown

**Comment by IcedCode** [comment]
I have updated the core class plugin which should fix this issue. If it pertains please recreate the issue

**Comment by IcedCode** [comment]
Just for future reference this wasn't actually a bug but it was actually power-ups within the game causing this
